<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <!-- outras propriedades -->
    </PropertyGroup>

    <ItemGroup>
        <!-- MANTENHA esta -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />

        <!-- ADICIONE esta (nova) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />

        <!-- SUBSTITUA esta (era preview, agora versão estável) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11" />

        <!-- MANTENHA esta -->
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AdministrandoAluguelDeVeiculos.Core\AdministrandoAluguelDeVeiculos.Core.csproj" />
    </ItemGroup>
</Project>
